/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const BusinessRole = IDL.Variant({
  'ca' : IDL.Null,
  'accountant' : IDL.Null,
  'admin' : IDL.Null,
});
export const BusinessUserRole = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Nat,
  'createdAt' : Time,
  'role' : BusinessRole,
  'invitedBy' : IDL.Principal,
  'userPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const TenantStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'suspended' : IDL.Null,
});
export const ClientTenant = IDL.Record({
  'id' : IDL.Nat,
  'status' : TenantStatus,
  'subscriptionEndDate' : Time,
  'subscriptionPlan' : IDL.Text,
  'businessName' : IDL.Text,
  'tenantId' : IDL.Text,
  'clientPrincipal' : IDL.Principal,
  'crmLeadId' : IDL.Opt(IDL.Nat),
  'provisionedAt' : Time,
  'subscriptionStartDate' : Time,
  'contactEmail' : IDL.Text,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'paymentMethod' : IDL.Text,
  'clientName' : IDL.Text,
  'createdAt' : Time,
  'subscriptionPlan' : IDL.Text,
  'orderId' : IDL.Text,
  'clientPrincipal' : IDL.Principal,
  'amountInr' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBusiness' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createRazorpayOrder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'getBusinessUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BusinessUserRole)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientTenants' : IDL.Func([], [IDL.Vec(ClientTenant)], ['query']),
  'getMyBusinessRole' : IDL.Func([IDL.Nat], [IDL.Opt(BusinessRole)], ['query']),
  'getMyTenant' : IDL.Func([], [IDL.Opt(ClientTenant)], ['query']),
  'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getPaymentSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'expiringIn30Days' : IDL.Nat,
          'suspendedAccounts' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'activeSubscriptions' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getRazorpayKeyId' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'inviteUserToBusinessRole' : IDL.Func(
      [IDL.Nat, IDL.Principal, BusinessRole],
      [IDL.Nat],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'provisionClientTenant' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'reactivateTenant' : IDL.Func([IDL.Text], [], []),
  'recordPayment' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'removeBusinessUser' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRazorpayConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'suspendTenant' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateTenantSubscription' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const BusinessRole = IDL.Variant({
    'ca' : IDL.Null,
    'accountant' : IDL.Null,
    'admin' : IDL.Null,
  });
  const BusinessUserRole = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Nat,
    'createdAt' : Time,
    'role' : BusinessRole,
    'invitedBy' : IDL.Principal,
    'userPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const TenantStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const ClientTenant = IDL.Record({
    'id' : IDL.Nat,
    'status' : TenantStatus,
    'subscriptionEndDate' : Time,
    'subscriptionPlan' : IDL.Text,
    'businessName' : IDL.Text,
    'tenantId' : IDL.Text,
    'clientPrincipal' : IDL.Principal,
    'crmLeadId' : IDL.Opt(IDL.Nat),
    'provisionedAt' : Time,
    'subscriptionStartDate' : Time,
    'contactEmail' : IDL.Text,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'paymentMethod' : IDL.Text,
    'clientName' : IDL.Text,
    'createdAt' : Time,
    'subscriptionPlan' : IDL.Text,
    'orderId' : IDL.Text,
    'clientPrincipal' : IDL.Principal,
    'amountInr' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBusiness' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createRazorpayOrder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'getBusinessUsers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BusinessUserRole)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientTenants' : IDL.Func([], [IDL.Vec(ClientTenant)], ['query']),
    'getMyBusinessRole' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BusinessRole)],
        ['query'],
      ),
    'getMyTenant' : IDL.Func([], [IDL.Opt(ClientTenant)], ['query']),
    'getPaymentRecords' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getPaymentSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'expiringIn30Days' : IDL.Nat,
            'suspendedAccounts' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'activeSubscriptions' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getRazorpayKeyId' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'inviteUserToBusinessRole' : IDL.Func(
        [IDL.Nat, IDL.Principal, BusinessRole],
        [IDL.Nat],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isRazorpayConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'provisionClientTenant' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'reactivateTenant' : IDL.Func([IDL.Text], [], []),
    'recordPayment' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'removeBusinessUser' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRazorpayConfiguration' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'suspendTenant' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateTenantSubscription' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };