/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BusinessRole = { 'ca' : null } |
  { 'accountant' : null } |
  { 'admin' : null };
export interface BusinessUserRole {
  'id' : bigint,
  'businessId' : bigint,
  'createdAt' : Time,
  'role' : BusinessRole,
  'invitedBy' : Principal,
  'userPrincipal' : Principal,
}
export interface ClientTenant {
  'id' : bigint,
  'status' : TenantStatus,
  'subscriptionEndDate' : Time,
  'subscriptionPlan' : string,
  'businessName' : string,
  'tenantId' : string,
  'clientPrincipal' : Principal,
  'crmLeadId' : [] | [bigint],
  'provisionedAt' : Time,
  'subscriptionStartDate' : Time,
  'contactEmail' : string,
}
export interface PaymentRecord {
  'id' : bigint,
  'paymentStatus' : string,
  'paymentMethod' : string,
  'clientName' : string,
  'createdAt' : Time,
  'subscriptionPlan' : string,
  'orderId' : string,
  'clientPrincipal' : Principal,
  'amountInr' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type TenantStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'suspended' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBusiness' : ActorMethod<[string, string, string, string], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createRazorpayOrder' : ActorMethod<[bigint, string, string], string>,
  'getBusinessUsers' : ActorMethod<[bigint], Array<BusinessUserRole>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientTenants' : ActorMethod<[], Array<ClientTenant>>,
  'getMyBusinessRole' : ActorMethod<[bigint], [] | [BusinessRole]>,
  'getMyTenant' : ActorMethod<[], [] | [ClientTenant]>,
  'getPaymentRecords' : ActorMethod<[], Array<PaymentRecord>>,
  'getPaymentSummary' : ActorMethod<
    [],
    {
      'expiringIn30Days' : bigint,
      'suspendedAccounts' : bigint,
      'totalRevenue' : bigint,
      'activeSubscriptions' : bigint,
    }
  >,
  'getRazorpayKeyId' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'inviteUserToBusinessRole' : ActorMethod<
    [bigint, Principal, BusinessRole],
    bigint
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isRazorpayConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'provisionClientTenant' : ActorMethod<
    [Principal, string, string, string, bigint],
    string
  >,
  'reactivateTenant' : ActorMethod<[string], undefined>,
  'recordPayment' : ActorMethod<
    [string, Principal, string, string, bigint, string],
    undefined
  >,
  'removeBusinessUser' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRazorpayConfiguration' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'suspendTenant' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateTenantSubscription' : ActorMethod<[string, string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];