/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Business {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'createdAt' : Time,
  'state' : string,
  'gstin' : string,
  'address' : string,
}
export interface Customer {
  'id' : bigint,
  'businessId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface DashboardData {
  'netGstPayable' : bigint,
  'recentInvoices' : Array<Invoice>,
  'currentMonthOutputGst' : bigint,
  'totalPayables' : bigint,
  'currentMonthInputGst' : bigint,
  'overdueInvoiceCount' : bigint,
  'totalReceivables' : bigint,
}
export interface Expense {
  'id' : bigint,
  'expenseDate' : Time,
  'businessId' : bigint,
  'createdAt' : Time,
  'description' : string,
  'gstAmount' : bigint,
  'vendorId' : [] | [bigint],
  'category' : string,
  'amount' : bigint,
}
export interface Invoice {
  'id' : bigint,
  'status' : InvoiceStatus,
  'businessId' : bigint,
  'cgst' : bigint,
  'igst' : bigint,
  'createdAt' : Time,
  'sgst' : bigint,
  'dueDate' : Time,
  'invoiceDate' : Time,
  'invoiceNumber' : string,
  'totalAmount' : bigint,
  'customerId' : bigint,
  'subtotal' : bigint,
}
export type InvoiceStatus = { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'draft' : null };
export interface Product {
  'id' : bigint,
  'stockQuantity' : bigint,
  'purchasePrice' : bigint,
  'businessId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'sellingPrice' : bigint,
  'hsnCode' : string,
  'gstRate' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface SubscriptionStatus {
  'invoiceCount' : bigint,
  'tier' : SubscriptionTier,
  'productCount' : bigint,
  'customerCount' : bigint,
}
export type SubscriptionTier = { 'free' : null } |
  { 'paid' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'businessId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPaymentToInvoice' : ActorMethod<
    [bigint, bigint, Time, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBusiness' : ActorMethod<[string, string, string, string], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createCustomer' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'createExpense' : ActorMethod<
    [bigint, [] | [bigint], string, bigint, bigint, Time, string],
    bigint
  >,
  'createInvoice' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      Time,
      Time,
      Array<[bigint, string, bigint, bigint, bigint]>,
    ],
    bigint
  >,
  'createProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, bigint],
    bigint
  >,
  'createVendor' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'deleteBusiness' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteInvoice' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'generateGstReport' : ActorMethod<[bigint, Time, Time], bigint>,
  'getBusiness' : ActorMethod<[bigint], Business>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[bigint], Customer>,
  'getCustomers' : ActorMethod<[bigint], Array<Customer>>,
  'getDashboardData' : ActorMethod<[bigint], DashboardData>,
  'getExpense' : ActorMethod<[bigint], Expense>,
  'getExpenses' : ActorMethod<[bigint], Array<Expense>>,
  'getInvoice' : ActorMethod<[bigint], Invoice>,
  'getInvoices' : ActorMethod<[bigint], Array<Invoice>>,
  'getMyBusinesses' : ActorMethod<[], Array<Business>>,
  'getOverdueInvoices' : ActorMethod<[bigint], Array<Invoice>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProducts' : ActorMethod<[bigint], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionStatus' : ActorMethod<[Principal], SubscriptionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendor' : ActorMethod<[bigint], Vendor>,
  'getVendors' : ActorMethod<[bigint], Array<Vendor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'queryAI' : ActorMethod<[bigint, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBusiness' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateExpense' : ActorMethod<
    [bigint, string, bigint, bigint, Time, string],
    undefined
  >,
  'updateInvoiceStatus' : ActorMethod<[bigint, InvoiceStatus], undefined>,
  'updateProduct' : ActorMethod<
    [bigint, string, string, bigint, bigint, bigint, bigint],
    undefined
  >,
  'updateVendor' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];