/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Business = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'state' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
});
export const BusinessRole = IDL.Variant({
  'ca' : IDL.Null,
  'accountant' : IDL.Null,
  'admin' : IDL.Null,
});
export const BusinessUserRole = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Nat,
  'createdAt' : Time,
  'role' : BusinessRole,
  'invitedBy' : IDL.Principal,
  'userPrincipal' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'expenseDate' : Time,
  'businessId' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
  'gstAmount' : IDL.Nat,
  'vendorId' : IDL.Opt(IDL.Nat),
  'category' : IDL.Text,
  'amount' : IDL.Nat,
});
export const InvoiceStatus = IDL.Variant({
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'draft' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'businessId' : IDL.Nat,
  'cgst' : IDL.Nat,
  'igst' : IDL.Nat,
  'createdAt' : Time,
  'sgst' : IDL.Nat,
  'dueDate' : Time,
  'invoiceDate' : Time,
  'invoiceNumber' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'customerId' : IDL.Nat,
  'subtotal' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'stockQuantity' : IDL.Nat,
  'purchasePrice' : IDL.Nat,
  'businessId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'sellingPrice' : IDL.Nat,
  'hsnCode' : IDL.Text,
  'gstRate' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'businessId' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPaymentToInvoice' : IDL.Func(
      [IDL.Nat, IDL.Nat, Time, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBusiness' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createExpense' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createInvoice' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        Time,
        Time,
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat)),
      ],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'createVendor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBusiness' : IDL.Func([IDL.Nat], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'generateGstReport' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
  'getBusiness' : IDL.Func([IDL.Nat], [Business], ['query']),
  'getBusinessUsers' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BusinessUserRole)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
  'getCustomers' : IDL.Func([IDL.Nat], [IDL.Vec(Customer)], ['query']),
  'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
  'getExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
  'getInvoices' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'getMyBusinessRole' : IDL.Func([IDL.Nat], [IDL.Opt(BusinessRole)], ['query']),
  'getMyBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
  'getOverdueInvoices' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
  'getVendors' : IDL.Func([IDL.Nat], [IDL.Vec(Vendor)], ['query']),
  'inviteUserToBusinessRole' : IDL.Func(
      [IDL.Nat, IDL.Principal, BusinessRole],
      [IDL.Nat],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBusinessUser' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBusiness' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateExpense' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Text],
      [],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func([IDL.Nat, InvoiceStatus], [], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'updateVendor' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Business = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'state' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
  });
  const BusinessRole = IDL.Variant({
    'ca' : IDL.Null,
    'accountant' : IDL.Null,
    'admin' : IDL.Null,
  });
  const BusinessUserRole = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Nat,
    'createdAt' : Time,
    'role' : BusinessRole,
    'invitedBy' : IDL.Principal,
    'userPrincipal' : IDL.Principal,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'expenseDate' : Time,
    'businessId' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
    'gstAmount' : IDL.Nat,
    'vendorId' : IDL.Opt(IDL.Nat),
    'category' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const InvoiceStatus = IDL.Variant({
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Invoice = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'businessId' : IDL.Nat,
    'cgst' : IDL.Nat,
    'igst' : IDL.Nat,
    'createdAt' : Time,
    'sgst' : IDL.Nat,
    'dueDate' : Time,
    'invoiceDate' : Time,
    'invoiceNumber' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'customerId' : IDL.Nat,
    'subtotal' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'stockQuantity' : IDL.Nat,
    'purchasePrice' : IDL.Nat,
    'businessId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'sellingPrice' : IDL.Nat,
    'hsnCode' : IDL.Text,
    'gstRate' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'businessId' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPaymentToInvoice' : IDL.Func(
        [IDL.Nat, IDL.Nat, Time, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBusiness' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createExpense' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Nat), IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createInvoice' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          Time,
          Time,
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat)),
        ],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'createVendor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBusiness' : IDL.Func([IDL.Nat], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteInvoice' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'generateGstReport' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
    'getBusiness' : IDL.Func([IDL.Nat], [Business], ['query']),
    'getBusinessUsers' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BusinessUserRole)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [Customer], ['query']),
    'getCustomers' : IDL.Func([IDL.Nat], [IDL.Vec(Customer)], ['query']),
    'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
    'getExpenses' : IDL.Func([IDL.Nat], [IDL.Vec(Expense)], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [Invoice], ['query']),
    'getInvoices' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
    'getMyBusinessRole' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(BusinessRole)],
        ['query'],
      ),
    'getMyBusinesses' : IDL.Func([], [IDL.Vec(Business)], ['query']),
    'getOverdueInvoices' : IDL.Func([IDL.Nat], [IDL.Vec(Invoice)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProducts' : IDL.Func([IDL.Nat], [IDL.Vec(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendor' : IDL.Func([IDL.Nat], [Vendor], ['query']),
    'getVendors' : IDL.Func([IDL.Nat], [IDL.Vec(Vendor)], ['query']),
    'inviteUserToBusinessRole' : IDL.Func(
        [IDL.Nat, IDL.Principal, BusinessRole],
        [IDL.Nat],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBusinessUser' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBusiness' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateExpense' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, Time, IDL.Text],
        [],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func([IDL.Nat, InvoiceStatus], [], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'updateVendor' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };