/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface DashboardData {
    netGstPayable: bigint;
    recentInvoices: Array<Invoice>;
    currentMonthOutputGst: bigint;
    totalPayables: bigint;
    currentMonthInputGst: bigint;
    overdueInvoiceCount: bigint;
    totalReceivables: bigint;
}
export interface Business {
    id: bigint;
    owner: Principal;
    name: string;
    createdAt: Time;
    state: string;
    gstin: string;
    address: string;
}
export interface Invoice {
    id: bigint;
    status: InvoiceStatus;
    businessId: bigint;
    cgst: bigint;
    igst: bigint;
    createdAt: Time;
    sgst: bigint;
    dueDate: Time;
    invoiceDate: Time;
    invoiceNumber: string;
    totalAmount: bigint;
    customerId: bigint;
    subtotal: bigint;
}
export interface Expense {
    id: bigint;
    expenseDate: Time;
    businessId: bigint;
    createdAt: Time;
    description: string;
    gstAmount: bigint;
    vendorId?: bigint;
    category: string;
    amount: bigint;
}
export interface Customer {
    id: bigint;
    businessId: bigint;
    name: string;
    createdAt: Time;
    email: string;
    gstin: string;
    address: string;
    phone: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Vendor {
    id: bigint;
    businessId: bigint;
    name: string;
    createdAt: Time;
    email: string;
    gstin: string;
    address: string;
    phone: string;
}
export interface SubscriptionStatus {
    invoiceCount: bigint;
    tier: SubscriptionTier;
    productCount: bigint;
    customerCount: bigint;
}
export interface Product {
    id: bigint;
    stockQuantity: bigint;
    purchasePrice: bigint;
    businessId: bigint;
    name: string;
    createdAt: Time;
    sellingPrice: bigint;
    hsnCode: string;
    gstRate: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum InvoiceStatus {
    paid = "paid",
    sent = "sent",
    overdue = "overdue",
    draft = "draft"
}
export enum SubscriptionTier {
    free = "free",
    paid = "paid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPaymentToInvoice(invoiceId: bigint, amount: bigint, paymentDate: Time, paymentMode: string, referenceNo: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBusiness(name: string, gstin: string, state: string, address: string): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createCustomer(businessId: bigint, name: string, gstin: string, phone: string, email: string, address: string): Promise<bigint>;
    createExpense(businessId: bigint, vendorId: bigint | null, category: string, amount: bigint, gstAmount: bigint, expenseDate: Time, description: string): Promise<bigint>;
    createInvoice(businessId: bigint, customerId: bigint, invoiceNumber: string, invoiceDate: Time, dueDate: Time, items: Array<[bigint, string, bigint, bigint, bigint]>): Promise<bigint>;
    createProduct(businessId: bigint, name: string, hsnCode: string, gstRate: bigint, purchasePrice: bigint, sellingPrice: bigint, stockQuantity: bigint): Promise<bigint>;
    createVendor(businessId: bigint, name: string, gstin: string, phone: string, email: string, address: string): Promise<bigint>;
    deleteBusiness(id: bigint): Promise<void>;
    deleteCustomer(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteInvoice(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    deleteVendor(id: bigint): Promise<void>;
    generateGstReport(businessId: bigint, periodStart: Time, periodEnd: Time): Promise<bigint>;
    getBusiness(id: bigint): Promise<Business>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: bigint): Promise<Customer>;
    getCustomers(businessId: bigint): Promise<Array<Customer>>;
    getDashboardData(businessId: bigint): Promise<DashboardData>;
    getExpense(id: bigint): Promise<Expense>;
    getExpenses(businessId: bigint): Promise<Array<Expense>>;
    getInvoice(id: bigint): Promise<Invoice>;
    getInvoices(businessId: bigint): Promise<Array<Invoice>>;
    getMyBusinesses(): Promise<Array<Business>>;
    getOverdueInvoices(businessId: bigint): Promise<Array<Invoice>>;
    getProduct(id: bigint): Promise<Product>;
    getProducts(businessId: bigint): Promise<Array<Product>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionStatus(userId: Principal): Promise<SubscriptionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendor(id: bigint): Promise<Vendor>;
    getVendors(businessId: bigint): Promise<Array<Vendor>>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    queryAI(businessId: bigint, userMessage: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateBusiness(id: bigint, name: string, gstin: string, state: string, address: string): Promise<void>;
    updateCustomer(id: bigint, name: string, gstin: string, phone: string, email: string, address: string): Promise<void>;
    updateExpense(id: bigint, category: string, amount: bigint, gstAmount: bigint, expenseDate: Time, description: string): Promise<void>;
    updateInvoiceStatus(id: bigint, status: InvoiceStatus): Promise<void>;
    updateProduct(id: bigint, name: string, hsnCode: string, gstRate: bigint, purchasePrice: bigint, sellingPrice: bigint, stockQuantity: bigint): Promise<void>;
    updateVendor(id: bigint, name: string, gstin: string, phone: string, email: string, address: string): Promise<void>;
}
import type { DashboardData as _DashboardData, Expense as _Expense, Invoice as _Invoice, InvoiceStatus as _InvoiceStatus, StripeSessionStatus as _StripeSessionStatus, SubscriptionStatus as _SubscriptionStatus, SubscriptionTier as _SubscriptionTier, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPaymentToInvoice(arg0: bigint, arg1: bigint, arg2: Time, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPaymentToInvoice(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPaymentToInvoice(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBusiness(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBusiness(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBusiness(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createExpense(arg0: bigint, arg1: bigint | null, arg2: string, arg3: bigint, arg4: bigint, arg5: Time, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(arg0, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createInvoice(arg0: bigint, arg1: bigint, arg2: string, arg3: Time, arg4: Time, arg5: Array<[bigint, string, bigint, bigint, bigint]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async createProduct(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createVendor(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteBusiness(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusiness(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteInvoice(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInvoice(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteVendor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVendor(arg0);
            return result;
        }
    }
    async generateGstReport(arg0: bigint, arg1: Time, arg2: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generateGstReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateGstReport(arg0, arg1, arg2);
            return result;
        }
    }
    async getBusiness(arg0: bigint): Promise<Business> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusiness(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: bigint): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getCustomers(arg0: bigint): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomers(arg0);
            return result;
        }
    }
    async getDashboardData(arg0: bigint): Promise<DashboardData> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardData(arg0);
                return from_candid_DashboardData_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardData(arg0);
            return from_candid_DashboardData_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpense(arg0: bigint): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_Expense_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_Expense_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpenses(arg0: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpenses(arg0);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpenses(arg0);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoice(arg0: bigint): Promise<Invoice> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_Invoice_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_Invoice_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoices(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoices(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoices(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBusinesses(): Promise<Array<Business>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBusinesses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBusinesses();
            return result;
        }
    }
    async getOverdueInvoices(arg0: bigint): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueInvoices(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueInvoices(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getProducts(arg0: bigint): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts(arg0);
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionStatus(arg0: Principal): Promise<SubscriptionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionStatus(arg0);
                return from_candid_SubscriptionStatus_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionStatus(arg0);
            return from_candid_SubscriptionStatus_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendor(arg0: bigint): Promise<Vendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendor(arg0);
            return result;
        }
    }
    async getVendors(arg0: bigint): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendors(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendors(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async queryAI(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.queryAI(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queryAI(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateBusiness(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusiness(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusiness(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateCustomer(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: Time, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateInvoiceStatus(arg0: bigint, arg1: InvoiceStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(arg0, to_candid_InvoiceStatus_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(arg0, to_candid_InvoiceStatus_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateVendor(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVendor(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
}
function from_candid_DashboardData_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardData): DashboardData {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionTier_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionTier): SubscriptionTier {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InvoiceStatus;
    businessId: bigint;
    cgst: bigint;
    igst: bigint;
    createdAt: _Time;
    sgst: bigint;
    dueDate: _Time;
    invoiceDate: _Time;
    invoiceNumber: string;
    totalAmount: bigint;
    customerId: bigint;
    subtotal: bigint;
}): {
    id: bigint;
    status: InvoiceStatus;
    businessId: bigint;
    cgst: bigint;
    igst: bigint;
    createdAt: Time;
    sgst: bigint;
    dueDate: Time;
    invoiceDate: Time;
    invoiceNumber: string;
    totalAmount: bigint;
    customerId: bigint;
    subtotal: bigint;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n12(_uploadFile, _downloadFile, value.status),
        businessId: value.businessId,
        cgst: value.cgst,
        igst: value.igst,
        createdAt: value.createdAt,
        sgst: value.sgst,
        dueDate: value.dueDate,
        invoiceDate: value.invoiceDate,
        invoiceNumber: value.invoiceNumber,
        totalAmount: value.totalAmount,
        customerId: value.customerId,
        subtotal: value.subtotal
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseDate: _Time;
    businessId: bigint;
    createdAt: _Time;
    description: string;
    gstAmount: bigint;
    vendorId: [] | [bigint];
    category: string;
    amount: bigint;
}): {
    id: bigint;
    expenseDate: Time;
    businessId: bigint;
    createdAt: Time;
    description: string;
    gstAmount: bigint;
    vendorId?: bigint;
    category: string;
    amount: bigint;
} {
    return {
        id: value.id,
        expenseDate: value.expenseDate,
        businessId: value.businessId,
        createdAt: value.createdAt,
        description: value.description,
        gstAmount: value.gstAmount,
        vendorId: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.vendorId)),
        category: value.category,
        amount: value.amount
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    invoiceCount: bigint;
    tier: _SubscriptionTier;
    productCount: bigint;
    customerCount: bigint;
}): {
    invoiceCount: bigint;
    tier: SubscriptionTier;
    productCount: bigint;
    customerCount: bigint;
} {
    return {
        invoiceCount: value.invoiceCount,
        tier: from_candid_SubscriptionTier_n24(_uploadFile, _downloadFile, value.tier),
        productCount: value.productCount,
        customerCount: value.customerCount
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    netGstPayable: bigint;
    recentInvoices: Array<_Invoice>;
    currentMonthOutputGst: bigint;
    totalPayables: bigint;
    currentMonthInputGst: bigint;
    overdueInvoiceCount: bigint;
    totalReceivables: bigint;
}): {
    netGstPayable: bigint;
    recentInvoices: Array<Invoice>;
    currentMonthOutputGst: bigint;
    totalPayables: bigint;
    currentMonthInputGst: bigint;
    overdueInvoiceCount: bigint;
    totalReceivables: bigint;
} {
    return {
        netGstPayable: value.netGstPayable,
        recentInvoices: from_candid_vec_n9(_uploadFile, _downloadFile, value.recentInvoices),
        currentMonthOutputGst: value.currentMonthOutputGst,
        totalPayables: value.totalPayables,
        currentMonthInputGst: value.currentMonthInputGst,
        overdueInvoiceCount: value.overdueInvoiceCount,
        totalReceivables: value.totalReceivables
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    draft: null;
}): InvoiceStatus {
    return "paid" in value ? InvoiceStatus.paid : "sent" in value ? InvoiceStatus.sent : "overdue" in value ? InvoiceStatus.overdue : "draft" in value ? InvoiceStatus.draft : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n20(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    free: null;
} | {
    paid: null;
}): SubscriptionTier {
    return "free" in value ? SubscriptionTier.free : "paid" in value ? SubscriptionTier.paid : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n10(_uploadFile, _downloadFile, x));
}
function to_candid_InvoiceStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    draft: null;
} {
    return value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.sent ? {
        sent: null
    } : value == InvoiceStatus.overdue ? {
        overdue: null
    } : value == InvoiceStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
